steps:
  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.2.0: ~

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: docker-login

  - label: "Security Scan"
    key: security_scan
    plugins:
      - secrets#v1.0.2:
          variables:
            GITHUB_TOKEN: GITHUB_TOKEN
      - ossf-scorecard#v1.0.1:
          github_token: $$GITHUB_TOKEN
