steps:
  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.1.0: ~

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files:
            - hooks/**

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: docker-login