#!/bin/bash

set -eu -o pipefail

logout_args=(logout)

if [ -n "${BUILDKITE_PLUGIN_DOCKER_LOGIN_SERVER:-}" ]; then
    logout_args+=("${BUILDKITE_PLUGIN_DOCKER_LOGIN_SERVER}")
fi

if [ "${BUILDKITE_PLUGIN_DOCKER_LOGIN_DISABLE_LOGOUT:-false}" = "false" ]; then
    docker "${logout_args[@]}"
fi

if [ "${BUILDKITE_PLUGIN_DOCKER_LOGIN_ISOLATE_CONFIG:-true}" = "true" ] &&
   [ -d "${BUILDKITE_DOCKER_LOGIN_TEMP_CONFIG}" ] ; then
    rm -rf "${BUILDKITE_DOCKER_LOGIN_TEMP_CONFIG}"
fi